#!/bin/sh
#
# @name Gazebo 1.8 kg measured-envelope quadrotor
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=uav985}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.212132
param set-default CA_ROTOR0_PY 0.212132
param set-default CA_ROTOR0_KM  0.025

param set-default CA_ROTOR1_PX -0.212132
param set-default CA_ROTOR1_PY -0.212132
param set-default CA_ROTOR1_KM  0.025

param set-default CA_ROTOR2_PX 0.212132
param set-default CA_ROTOR2_PY -0.212132
param set-default CA_ROTOR2_KM -0.025

param set-default CA_ROTOR3_PX -0.212132
param set-default CA_ROTOR3_PY 0.212132
param set-default CA_ROTOR3_KM -0.025

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.57
param set-default MPC_TKO_RAMP_T 1.0
param set-default NAV_DLL_ACT 0
param set-default COM_RC_IN_MODE 4
param set-default MIS_TKO_ALT_MAX 1.0

param set-default MC_RATE_CTRL_T 1
param set-default MC_MSMC_CFG 1

param set-default MC_MPC_J_R 0.04197
param set-default MC_MPC_J_P 0.03669
param set-default MC_MPC_J_Y 0.05285

param set-default MC_MPC_EFF_R 7.107
param set-default MC_MPC_EFF_P 7.107
param set-default MC_MPC_EFF_Y 1.184

param set-default MC_MPC_GYRO 1.0
param set-default MC_MPC_TAU 0.025
param set-default MC_MPC_HORIZON 8

param set-default MC_MPC_R_R 1.0
param set-default MC_MPC_R_P 1.0
param set-default MC_MPC_R_Y 1.0

param set-default MC_MPC_DU_R 0.05
param set-default MC_MPC_DU_P 0.05
param set-default MC_MPC_DU_Y 0.05

param set-default MC_MPC_SLEW 10.0

param set-default MC_MPC_I_R 0.0
param set-default MC_MPC_I_P 0.0
param set-default MC_MPC_I_Y 0.0

param set-default MC_MPC_ILIM_R 0.05
param set-default MC_MPC_ILIM_P 0.05
param set-default MC_MPC_ILIM_Y 0.05

param set-default MC_MPC_TMAX_R 0.20
param set-default MC_MPC_TMAX_P 0.20
param set-default MC_MPC_TMAX_Y 0.10

param set-default MC_MSMC_J_R 0.04197
param set-default MC_MSMC_J_P 0.03669
param set-default MC_MSMC_J_Y 0.05285

param set-default MC_MSMC_EFF_R 7.107
param set-default MC_MSMC_EFF_P 7.107
param set-default MC_MSMC_EFF_Y 1.184

param set-default MC_MSMC_C_R 2.0
param set-default MC_MSMC_C_P 2.0
param set-default MC_MSMC_C_Y 1.0

param set-default MC_MSMC_ETA_R 7.0
param set-default MC_MSMC_ETA_P 8.2
param set-default MC_MSMC_ETA_Y 0.7

param set-default MC_MSMC_BND_R 0.50
param set-default MC_MSMC_BND_P 0.50
param set-default MC_MSMC_BND_Y 0.20

param set-default MC_MSMC_KS_R 1.0
param set-default MC_MSMC_KS_P 1.0
param set-default MC_MSMC_KS_Y 1.0
param set-default MC_MSMC_RSPD_L 0.0

param set-default MC_MSMC_ILIM_R 0.30
param set-default MC_MSMC_ILIM_P 0.30
param set-default MC_MSMC_ILIM_Y 0.30

param set-default MC_MSMC_TMAX_R 0.20
param set-default MC_MSMC_TMAX_P 0.20
param set-default MC_MSMC_TMAX_Y 0.10

param set-default MC_SMC_LPF 20.0
param set-default MC_SMC_SLEW 15.0
